-- Database: HDR_GATEWAY_DB

-- DROP DATABASE "HDR_GATEWAY_DB";

CREATE DATABASE "HDR_GATEWAY_DB"
    WITH 
    OWNER = "HDR_DB_ACCESS"
ENCODING = 'UTF8'
    LC_COLLATE = 'English_United Kingdom.1252'
    LC_CTYPE = 'English_United Kingdom.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;